### ISSUE TITLE
"Close all tabs" closes active tab

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla-extensions/firefox-voice#1315]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
Several tabs are opened.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Close all tabs" command.

### Expected result:
Firefox windows tries to close and a confirmation to close the tabs is displayed.

### Actual result:
Only the active tab is closed.

### Notes:
Reproduced on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-16).
"Close this window" and "Close window" commands close the Firefox window, without displaying the confirmation to close the opened tabs.

![1](https://user-images.githubusercontent.com/54401091/76863315-fc2dc680-6867-11ea-9c0c-625fe7252c0c.gif)

**Comment by JanviMahajan14** [comment]
Hi @alexandra-martin I would like to work on this issue. Pls assign this to me.

**Comment by alexandra-martin** [comment]
@JanviMahajan14 @ianb or @awallin can help you with that.

**Comment by ianb** [comment]
@JanviMahajan14 You got it. You should either just not close the active tab, or close everything and then open `about:blank`

**Comment by JanviMahajan14** [comment]
Thanks @ianb  I am working on this.

**Comment by xlisachan** [comment]
@ianb I think the pull request #1313 that @shreyaa-s submitted this morning would solve this and #1298

**Comment by ianb** [comment]
It looks like we don't actually have any "close all tabs" intent at all. We have a test example, but that example only works because "all" is ignored as a stopword (one of the words in `english.toml`).

There's a "close all selected tabs" intent. I'm not sure we want a "close all tabs" intent, as it's not a sensible thing to want to do. You can close the window (which would close the tabs) or exit Firefox (which will close tabs in all windows), or select all tabs and close them.

Just removing the example is probably sufficient.

**Comment by Simpcyclassy** [comment]
This has been closed here https://github.com/mozilla-extensions/firefox-voice/issues/1751
